name: peklo_ticket
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  go_router: ^16.2.5
  flutter_animate: ^4.5.2
  pinput: ^5.0.2
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.1
  collection: ^1.19.1
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/sounds/
  shaders:
    - assets/shaders/wave.frag

flutter_gen:
  output: lib/gen/
